backend:
  name: git-gateway
#  branch: master

publish_mode: editorial_workflow
media_folder: content/images
public_folder: /images

collections:
  - name: articles
    label: Articles
    label_singular: Article
    folder: content
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: md
    format: frontmatter
    fields:
      - label: Title
        name: title
        widget: string
      - label: Slug
        name: slug
        widget: string
      - label: URL name
        name: urlname
        widget: string
      - label: Date
        name: date
        widget: datetime
        timeFormat: false
      - label: Author
        name: author
        widget: string
